// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zinga.Database;

#nullable disable

namespace Zinga.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20260331221227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zinga.Database.Constraint", b =>
                {
                    b.Property<int>("ConstraintID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConstraintID"));

                    b.Property<string>("AkasJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LogicSuco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<string>("Shortcut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SvgDefsSuco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SvgSuco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariablesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConstraintID");

                    b.ToTable("Constraints");
                });

            modelBuilder.Entity("Zinga.Database.Puzzle", b =>
                {
                    b.Property<int>("PuzzleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuzzleID"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Generated")
                        .HasColumnType("bit");

                    b.Property<string>("GivensJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinksJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PuzzleID");

                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("Zinga.Database.PuzzleConstraint", b =>
                {
                    b.Property<int>("PuzzleConstraintID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuzzleConstraintID"));

                    b.Property<int>("ConstraintID")
                        .HasColumnType("int");

                    b.Property<int>("PuzzleID")
                        .HasColumnType("int");

                    b.Property<string>("ValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PuzzleConstraintID");

                    b.ToTable("PuzzleConstraints");
                });
#pragma warning restore 612, 618
        }
    }
}
